### ISSUE TITLE
Remove ability to rename queues

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_automated_ingest#107]
Renaming Celery queues is rarely needed (if ever) and should be baked into the application. With this change should come a renaming of the queues from restart, path, and file to more descriptive names.

**Comment by holtgrewe** [comment]
Hi, I have a use case for this which is as follows.

- I have multiple instruments that I need to import from.
- I want to use one iRODS user per instrument.
- I'd rather keep the number of redis databases to the default.

Could this change be reverted?

**Comment by trel** [comment]
Anything is possible...  :) 

Perhaps you can explain a bit more?


I don't understand the connection between the queue name(s) and your use case - the queue name is/should be an implementation detail that doesn't matter to the interface?

- Multiple instruments means... different import source locations - meaning different jobs?
- Different instruments can use different 'as_user' values
- Different/multiple jobs already use the same single redis database?

**Comment by holtgrewe** [comment]
- I'm running one celery process for each instrument, each running as a different user.
- I'm using periodic jobs.
- I want to route the jobs from instrument A to the celery process running as user A etc.
- With the old interface, I could have a single redis database with many queues (instrument count x 3). Now I would need instrument count many redis databases with 3 queues each.

**Comment by trel** [comment]
Got it.

You don't want jobs in the queue to be picked up by workers on a different machine.
So, you need different queues.

I agree - the easiest way to provide this functionality is the revert.

We'll continue to argue internally about the names of those queues - I find them a bit unhelpful/expressive at the moment.

Thanks!

**Comment by trel** [comment]
Reverted!

**Comment by holtgrewe** [comment]
Thanks!
