### ISSUE TITLE
add new command-line parameter for additional redis annotation

### ISSUE THREAD

**Issue by trel** [irods/irods_capability_automated_ingest#11]
- should be named...  `--append_json` or `--redis_annotation`?

- should take a well-formed json object (including brackets)
   - should complain if not well-formed json

- appended information should pass through to any derivative jobs (e.g. scanning a directory should pass annotations to new file scanning redis jobs)

**Comment by trel** [comment]
Possibly moot with the move to celery (#14)?

Does celery allow for passthrough job annotation?

**Comment by xu-hao** [comment]
celery can pass arbitrary arguments, this is currently still implemented in
celery

**Comment by trel** [comment]
Ah, very good.  If this is implemented completely, please close this.
