### ISSUE TITLE
Ingest cannot start with as_user() returning a rodsuser account

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods_capability_automated_ingest#114]
The framework tests for the existence of the root collection '/' which is not readable by a rodsuser account which then throws an excption:
https://github.com/irods/irods_capability_automated_ingest/blob/master/irods_capability_automated_ingest/sync_irods.py#L23

**Comment by trel** [comment]
@alanking Can we close this?  And therefore #138 too?

**Comment by alanking** [comment]
I don't remember why we left this open, so I think it can be closed.

I think the original reasoning for the root collection check was a false premise anyway.

**Comment by trel** [comment]
Okay, closing and marking the other as duplicate.    We'll make a new issue if it comes up again.
