### ISSUE TITLE
Move all non-PEP event_handler methods to start options

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_automated_ingest#118]
Everything in this table should be a Start option:

| method |  effect  | default (current) | default (new!) |
| ----   |   ----- |  ----- | ----- |
| as_user |   takes action as this iRODS user |  authenticated user | (no change) |
| target_path | set mount path on the irods server which can be different from client mount path | client mount path | (no change) |
| to_resource | defines  target resource request of operation |  as provided by client environment | (no change) |
| operation | defines the mode of operation |  `Operation.REGISTER_SYNC` | `register_sync` (see below) |
| max_retries | defines max number of retries on failure | 0 | (no change) |
| timeout | defines seconds until job times out | 3600 | (no change) |
| delay | defines seconds between retries | 0 | (no change) |

Once implemented, these methods will be ignored in any existing event_handlers.

Operation will go from an Enum to a lowercase string:

| enum (current) | start option (new) |
| ----   |   ----- |
| `Operation.REGISTER_SYNC` (default)   | `register_sync` (default) |
| `Operation.REGISTER_AS_REPLICA_SYNC`  | `register_as_replica_sync` |
| `Operation.PUT`  | `put` |
| `Operation.PUT_SYNC`  | `put_sync` |
| `Operation.PUT_APPEND`  | `put_append` |
| `Operation.NO_OP` | `no_op` |

**Comment by alanking** [comment]
I now disagree with this suggestion. The event handler file is a good place to put all the configuration and custom code for modifying and extending behavior of automated ingest jobs. We could possibly support overriding things with command line options (which would then be submitted as part of the `meta` map) but I no longer think the event handler methods should be removed.

**Comment by trel** [comment]
very good.   i think we can close this.

**Comment by korydraughn** [comment]
Agreed.
