### ISSUE TITLE
Allow to filter files for upload?

### ISSUE THREAD

**Issue by holtgrewe** [irods/irods_capability_automated_ingest#140]
Is it possible to filter which files should be transferred?

Illumina sequencers write out thousand JPEGs that are useless once a run has completed successfully. I don't want to import them into iRODS.

**Comment by holtgrewe** [comment]
There are three `exlude_*` parameters for the CLI that allow to do this outside of Python already.

https://github.com/irods/irods_capability_automated_ingest/blob/fa3c81d78752f40abdbb14717cc5fae10c6cb706/irods_capability_automated_ingest/irods_sync.py#L87

It would be very helpful to also ignore whole directories from Python during crawling. Illumina sequencer output directories contain a "Thumbnail_Images" folder that is not important after the sequencer is done but contains tens of thousands of  small JPEG files that nobody wants to see any more.

**Comment by trel** [comment]
A `pre_job` method to handle this has been created in https://github.com/irods/irods_capability_automated_ingest/issues/142

**Comment by d-w-moore** [comment]
Is #142 related - I don't see the pre_job defined there , maybe a different issue / pull  / commit ?

**Comment by d-w-moore** [comment]
@holtgrewe I believe the options `--exclude_file_name` and `--exclude_directory_name` already provide the functionality asked for in this issue ? Each accepts a list of regular expressions, which seems adequate to the purpose, at least by my understanding. Please correct me if I'm not getting the import of the question.

**Comment by trel** [comment]
#142 is about gaining the ability to 'skip' (rather than error out) for whatever arbitrary reason the programmer/user decides to not move ahead with the job.   That functionality could be used to satisfy this requested functionality for 'filter'.

**Comment by d-w-moore** [comment]
Except you would have to reject all of the upload paths (based on whatever matching criteria) that had been allotted to that task, or you cannot really cancel the entire task as a unit.  You'd be rejecting others that had not matched. Am I correct on that?

**Comment by trel** [comment]
wouldn't each worker run the pre_job() before it does the work for a particular job that it pulled out of the queue?    if so, it could match some criteria (or not) and skip if desired...        or are my loops tangled?

**Comment by d-w-moore** [comment]
Hm don't know, I'll look to see if I maybe misunderstood --files-per-task [=50 default]  @alanking ? .We can discuss tomorrow.

**Comment by alanking** [comment]
I think that `--exclude_directory_name` may get the job done. It takes a regular expression, so you can just exclude the directory by name if it is known ahead of time.

As for the `pre_job` discussion, this is run before the overall sync task (this is in the `restart` task):
https://github.com/irods/irods_capability_automated_ingest/blob/e1d3246b11a0ecab2a856c42ac3746a3bcd70a32/irods_capability_automated_ingest/sync_task.py#L175-L178

So, `pre_job` does not run on each task. That would be `task_prerun` (which... doesn't seem to do much in our case):
https://github.com/irods/irods_capability_automated_ingest/blob/e1d3246b11a0ecab2a856c42ac3746a3bcd70a32/irods_capability_automated_ingest/sync_task.py#L27-L42

More information on that here: https://docs.celeryq.dev/en/stable/userguide/signals.html#task-prerun

**Comment by trel** [comment]
Agreed, it sounds like `--exclude_file_name` and `--exclude_directory_name` are exactly what is needed.

@holtgrewe please advise.

We'll plan to close this unless we hear from you.

**Comment by alanking** [comment]
Closing this one. We can open a new issue should more be required from this request.
