### ISSUE TITLE
verify / validate whether event handler exists and valid or not

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#17]
Currently,   I can give handler name that does not exist due to either typo or sometime it is removed when we get latest code from github repositry with git pull command and then we run the ingest command, it does not report any error indicating that it is successfully completed.

date; python -m irods_capability_automated_ingest.irods_sync start <source directory> <collection name> --event_handler XYZ_eventhandler --log_filename <log filename> --log_level ERROR --job_name ingest --append_json '"uid:d05a0c4454b9e08ff6e4f156ec0"' --timeout 3600 --redis_host xx.xxx.xx.xx --redis_port xxxx --redis_db 0 --synchronous --all

In this example, if XYZ_eventhandler is not exist, it should report an error something like "event handler XYZ_eventhandler.py" does not exist."

**Comment by alanking** [comment]
Received the following error message when running with a non-existent event_handler:
```
ImportError: No module named 'non_existent_event_handler'
```
No jobs were leftover on the queue.
