### ISSUE TITLE
add a switch --showprogress to enable/disable

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#18]
Add a switch --showprogress to enable/disable so that if we are running ingest in irods, it can be used as --showprogress but when it is invoked from other tools such as pipeline tools or jenkins, then it is not required progressbar so can be disabled.

Probably default is disabled.

date; python -m irods_capability_automated_ingest.irods_sync start <source directory> <collection name> --event_handler XYZ_eventhandler --log_filename <log filename> --log_level ERROR --job_name ingest --append_json '"uid:d05a0c4454b9e08ff6e4f156ec0"' --timeout 3600 --redis_host xx.xxx.xx.xx --redis_port xxxx --redis_db 0 --synchronous --all --showprogress

[Elapsed Time: 0:01:05] |####################################################################################################| (Time:  0:01:05) count:  5e+04 tasks: ------ failures: ------ retries: ------

**Comment by trel** [comment]
I recommend:
 - `--progress` is the name
 - disabled by default
 - only apply if `--synchronous` is enabled
