### ISSUE TITLE
Document when event handlers are triggered

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_capability_automated_ingest#183]

**Comment by alanking** [comment]
@korydraughn - Do you recall what this issue means? I do not understand what is meant by "event handlers" being "triggered". Perhaps this was referring to the client-side "PEP"-like methods?

**Comment by korydraughn** [comment]
Yes. I was referring to the (client-side) PEPs in the ingest tool.

**Comment by alanking** [comment]
Actually, this is illuminating. The pre- and post-hook methods could be properly called the Event Handlers. The other event handler methods are more like... configuration, or behavioral modifiers, for a sync job. I'll update some wording in the documentation to reflect this.

**Comment by korydraughn** [comment]
Sounds good to me.
