### ISSUE TITLE
add --notification switch to send an email notification

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#19]
Add --notification switch to send an email notification either to send simple one like ingest started and ingest completed or with log file attached.

Probably default is disabled.

date; python -m irods_capability_automated_ingest.irods_sync start <source directory> <collection name> --event_handler XYZ_eventhandler --log_filename <log filename> --log_level ERROR --job_name ingest --append_json '"uid:d05a0c4454b9e08ff6e4f156ec0"' --timeout 3600 --redis_host xx.xxx.xx.xx --redis_port xxxx --redis_db 0 --synchronous --all --notification

**Comment by trel** [comment]
For this to work, it would require much more defined configuration (target email, protocol, payload, etc.)...

However, if the `--synchronous` flag already only returns when the ingest is complete, the calling script could/should be the one to do any notification.

I think this feature should be left to the caller - not the ingest tool itself.

**Comment by xu-hao** [comment]
can be implemented using the post_job method
