### ISSUE TITLE
Add multithreaded read and write from S3 to iRODS for ```PUT``` and ```PUT_SYNC```

### ISSUE THREAD

**Issue by avkrishnamurthy** [irods/irods_capability_automated_ingest#207]
Currently, the ```PUT``` and ```PUT_SYNC``` operations for objects coming from an S3 bucket work using a single-stream read and write into iRODS, which is very slow for large files. Adding a multithreaded way to read the object from the S3 bucket and write it into iRODS will speed this up.

**Comment by avkrishnamurthy** [comment]
I think it can be closed. If something worrying comes from the performance results, it could be addressed in a new issue, or in the issue I will create soon about refactoring sync_irods.py and the scanner.

**Comment by alanking** [comment]
Agreed. Please close!

**Comment by trel** [comment]
very nice.
