### ISSUE TITLE
metadata.py in examples uses Operation.REGISTER instead of Operation.REGISTER_SYNC

### ISSUE THREAD

**Issue by avkrishnamurthy** [irods/irods_capability_automated_ingest#212]
Leads to attribution error when trying to use as event handler.

**Comment by alanking** [comment]
@avkrishnamurthy - Was this found during testing? Just trying to figure out how to label this.

**Comment by avkrishnamurthy** [comment]
> @avkrishnamurthy - Was this found during testing? Just trying to figure out how to label this.

I guess you could call it that. I tried using the metadata.py event handler to better understand what the metadata related functions in sync_irods.py were doing by looking at the logging, and I got en error when I used it which is how I found it.

**Comment by alanking** [comment]
Eh, let's just call it a bug. Thanks!
