### ISSUE TITLE
Update documentation (and Dockerfiles) in ./docker/ingest-test

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_automated_ingest#216]
The instructions for running tests apart from Compose appear to be out of date and actually don't work. We need to make some adjustments so that these are true again (or perhaps just remove them). This is extremely low priority.

**Comment by trel** [comment]
perhaps also 0.5.0 while you're making sure things are working...

**Comment by alanking** [comment]
Sure. The Compose instructions mostly work (I had to use the `compose` plugin instead of `docker-compose`), so, I'll just try to reverse-engineer some instructions.

**Comment by alanking** [comment]
I'm leaning toward removing the non-Compose instructions. We use Compose for testing in many projects now and do not provide instructions for running it otherwise. Thoughts?

**Comment by trel** [comment]
Yes, please let's just simplify and standardize on docker compose.   That feels easy enough and good.
