### ISSUE TITLE
Document using PRC client settings

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_automated_ingest#229]
There are some PRC client settings (https://github.com/irods/python-irodsclient/tree/v2.0.1?tab=readme-ov-file#python-irods-client-settings-file) which are needed for correct behavior in some situations. We need to document these for this client as well or at least make reference to the PRC's README on the subject so that users can correctly configure their environments.

**Comment by alanking** [comment]
Hmm... I think I (accidentally?) addressed this in this commit: https://github.com/irods/irods_capability_automated_ingest/commit/d3c95b6d9652bf5274b52dab8f008e06ca67288b Maybe we just link this to the relevant PR and call it done...

**Comment by trel** [comment]
sounds good.   less work is good work.

**Comment by korydraughn** [comment]
Agreed.

**Comment by alanking** [comment]
Nice. Addressed in https://github.com/irods/irods_capability_automated_ingest/pull/233. Closing.
