### ISSUE TITLE
investigate on disabling prefetch for ingest performance improvement

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#23]
Investigate whether disabling prefetch will improve ingest performance using `-Ofair` and below environment variables.

```
export CELERYD_PREFETCH_MULTIPLIER=1
export CELERY_ACKS_LATE=True

celery -A irods_capability_automated_ingest.sync_task worker -l error -Ofair -Q restart,path,file -c 32 &
```

**Comment by alanking** [comment]
I think this is more of a documentation exercise. I'll scoop this in my documentation effort.
