### ISSUE TITLE
sync tool hangs when given invalid --log_filename target

### ISSUE THREAD

**Issue by trel** [irods/irods_capability_automated_ingest#24]
Hangs with invalid path name (`/gpfs/mdadm/irods/log/`) for log target:

(irodssync) [root@dtp13 irodssync]# python -m irods_capability_automated_ingest.irods_sync start "/gpfs/appfs1/test_deepak_src" "/sc1dtpZone/home/rods/gpfs/appfs1/test_deepak_src" --event_handler ingest_eventhandler --log_filename /gpfs/mdadm/irods/log/deepak_automated_ingest.log --log_level ERROR --job_name ingest --append_json '"uid:201806d05a0c4454b9e08ff6e4f156ec0"' --timeout 3600 --redis_host 10.164.67.18 --redis_port 6379 --redis_db 0 --synchronous --all

 [Elapsed Time: 0:01:49] |                                                                                                   | (ETA:  --:--:--) count:      1 tasks:      1 failures: ------ retries: ------

**Comment by masilamani** [comment]
This issue happens for invalid source directory path too.  As part of adding pre and post job level handler/module, it should do checks whether source directory and log path is valid or not.

**Comment by alanking** [comment]
Providing an invalid path to `--log_filename` results in:
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/fake/ingest.log'
```
Providing an empty path results in:
```
irods_sync.py start: error: argument --log_filename: expected one argument
```
