### ISSUE TITLE
docker: Remove `irods-cockroachdb`

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_automated_ingest#245]
This directory contains .deb files. I fear it is too late to erase the files from history as it will update every sha since the one in which they were commited: https://github.com/irods/irods_capability_automated_ingest/commit/0a89cac5efd9c56a83095d6aedabda60ec493e2e

The `irods-postgresql` directory should also be removed.

**Comment by trel** [comment]
10MB!   gah.
