### ISSUE TITLE
Investigate need for `time.sleep` after calling `os.makedirs`

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_automated_ingest#280]
When I was writing tests for #48, I ran across a strange situation in which the Celery workers - during a sync job - do not see a directory tree (with some files) that I created in a Python `unittest.setUp` method... unless I sleep for some amount of time between creating the directories and starting the sync job. Through some light experimentation, I have found that a sleep as little as 1 second keeps things working, but I do not know how short the sleep can actually be while things continue to work.

The directories being created are inside a Docker volume, so I'm not sure if that has anything to do with it.

**Comment by alanking** [comment]
The same seems to be true for S3 buckets in some S3 sync tests I've been writing. Very strange.

**Comment by trel** [comment]
sounds like systems are lying/optimizing and you're catching them in it...

**Comment by alanking** [comment]
The issue is that the Celery workers are not actually ready to execute tasks in time when the tests start running. They take a full second or more to "mingle" (coordinate with other Celery nodes). It seems strange to me that this would cause problems (why not wait to do work until they're actually ready?) but we don't need to mingle in the test workers anyway because they assume they are "all alone".
