### ISSUE TITLE
Add a new switches to exclude given list of files/files pattern or directories/directories pattern

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#29]
Add a new switches to exclude given list of files/files pattern or directories/directories pattern. Example,  we want to exclude ".snapshot" directories  and sub-directories in the iRODS ingest but currently it does not support to exclude files or directory with regular expression or comma-lists similar --exclude_file_type "socket, character, pipe, block" switch.

**Comment by trel** [comment]
We cannot use comma separated values for listings of directories or files - there could be a comma in the file/directory names themselves.
