### ISSUE TITLE
Multiple errors in the ingest log

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#34]
Found the following multiple errors frequently in the ingest log While running ingest for a large number of files.

- WRONG RESOURCE OR PATH
- CAT_NAME_EXISTS_AS_DATAOBJ
- COULD NOT RECEIVE SERVER RESPONSE
- No such file or directory
- KeyError (516002) UNIX_FILE_STAT_ERR No such file or directory

**Comment by trel** [comment]
We have addressed many of these already.  Specific examples of problems can be addressed with their own issue.  Closing for now.
