### ISSUE TITLE
ingesting files names with special characters

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#40]
- [x] Handle register sync
- [x] Handle put
- [x] Add test for register sync
- [x] Add test for put

---
Ingesting files names with special characters throws an error "UnicodeEncodeError('utf-8', 'lock:sync_file:"

Example files:

Test_?f?[?^?x?[?X?A?b?v?f?[?g??????.doc
Test_????.zip
Test_}.ppt
?e?[?u???A?_Test.txt

Registering these files using ireg works fine.

**Comment by trel** [comment]
Planning to handle this by storing a surrogate logical data_object name in the catalog:
```
logical_path: <full_path_to_collection>/irods_UnicodeEncodeError_<UUID1>
physical_path: <full_path_to_directory>/irods_UnicodeEncodeError_<UUID1>
```


And storing information about the original badfilename in the AVU for that data_object:
```
A: irods::automated_ingest::UnicodeEncodeError
V: YXNkZmFzYXNkZmFzZmRzZmFzNTR3aHdnMmdnMzM0ZzIzMmhkCg==
U: python3.base64.64encode(str)
```

This will store all the original information about the badly named file in the catalog, losslessly.

Another tool can re-inflate the information when necessary.

**Comment by trel** [comment]
We need to use base64 encoding of the physical path, rather than uuid, in both the logical path and the physical path in the catalog so that updates can find the same file again the next time.  The uuid is randomized and cannot be reproduced on the next run.
