### ISSUE TITLE
Running asynchronous ingest job is not showing up in the list job command output

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#53]
Running asynchronous ingest job is not showing up in the list job command output.

python -m irods_capability_automated_ingest.irods_sync start <sourcedirectory> <collection> --event_handler <eventhandler> --log_filename /var/lib/irods/log/automated_ingest.log --log_level ERROR --job_name ingest_system --redis_host <hostname> --redis_port 6379 --redis_db 0 --irods_idle_disconnect_seconds 300  --ignore_cache

After running the ingest job,  running the below command is not showing up in the output:

python -m irods_capability_automated_ingest.irods_sync list        --redis_host <hostname> --redis_port 6379 --redis_db 0

But running stop job commnand appears that it stopped.
python -m irods_capability_automated_ingest.irods_sync stop ingest --redis_host <hostname> --redis_port 6379 --redis_db 0

100% (638511 of 638511) |##########################################################################################################################################################################| Elapsed Time: 0:04:04 Time:  0:04:04

Then, running iquest count command shows the count of ingested files is increasing which indicates that it did not stop.

iquest "SELECT COUNT(DATA_NAME) WHERE COLL_NAME like '%<collectionname%'"

**Comment by alanking** [comment]
Using the `--redis_host` option requires that you provide a value. Your job probably did not start because of an error:
```
irods_sync.py start: error: argument --redis_host: expected one argument
```
Please confirm that things are working when a `--redis_host` value is provided.

**Comment by alanking** [comment]
This issue is resolved using the suggestions in the previous comment. Closing.
