### ISSUE TITLE
Issue with broken symbolic - not consistent between Ingest and iscan

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#54]
iRODS ingest tool is able to ingest broken symbolic link and it works fine.    But after initial ingest is run, running iscan -rd <collection name> does not consider broken symbolic link object as valid object and returns as deleted

Physical file <symbolic link fil with path> on server <irods host> is missing, corresponding to iRODS object <iRODS object name for symbolic link>

**Comment by trel** [comment]
What would you suggest `iscan -rd` do?  It cannot know if the file is real or not -- all it sees is a bad symlink on the disk.

Add a flag to not report broken symlinks?

Seems a wrapper script may be a better solution?  Check if reported file is a symlink on disk and skip it?

**Comment by alanking** [comment]
I don't think `iscan` should be interested in metadata annotated by the ingest tool. I think `iscan` is right to follow the symlink and indicate that the data does not exist. As @trel said, all it sees is a bad symlink, and a wrapper script can handle ignoring these results if desired.
