### ISSUE TITLE
CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME error in the ingest log

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#55]
The ingest log has many CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME error, even though reported file path in the error is ingested by ingest job.  Looks like in somecase same file is trying to ingest by more than one celery worker and then throws this error.

First,  it should not be processed by more than one celery workers.   Even if it does, it should update it without throwing this error.

**Comment by alanking** [comment]
Multiple celery workers cannot claim the same path from the _same queue_. It seems more likely that multiple scanners are running on the same source and pointing at different Redis databases (i.e. different queues). In such a scenario, none of the scanners are aware of what the others have scanned. They are all attempting to create data objects in the single iRODS catalog, so the error would be correctly reporting that multiple data objects of the same name are being created.

Can you confirm whether multiple ingest jobs were being run on the same source directory? Do you have a proposal for the correct behavior?

**Comment by trel** [comment]
closing this - no action to take at this time.
