### ISSUE TITLE
Remove --append_json

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_automated_ingest#60]
Capture the use case for `--append_json` and provide an example for the README. Currently, appends JSON values to the append_json key in Redis.

**Comment by alanking** [comment]
This feature appears to have disappeared at some point. There are `append_json` references in the example event handlers and the `--append_json` option remains in `irods_sync`, but it is not referenced at all in the Celery tasks. There is one test for this feature that does not confirm anything about what it does - just that the ingest job does not fail.

Perhaps we should just remove this option...

**Comment by korydraughn** [comment]
If we can't determine what use-case it solves, then let's remove it.

To add to that, no one is asking for that option either. Perhaps it was disabled on purpose.

**Comment by alanking** [comment]
Alright, I've renamed the issue and given it a deprecation label. Given that the feature doesn't do anything, I think we can just remove it. No need for a deprecation step because it basically does not exist anyway.

**Comment by trel** [comment]
original issue... https://github.com/irods/irods_capability_automated_ingest/issues/11
