### ISSUE TITLE
CAT_NAME_EXISTS_AS_DATAOBJ error in the delta ingest

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_automated_ingest#66]
The ingest log has CAT_NAME_EXISTS_AS_DATAOBJ error when we run the delta ingest for the sub-directory/files that exist with the same name under the different parent directory.

Is it using fully qualified name for file path or relative path which causes this error "CAT_NAME_EXISTS_AS_DATAOBJ" ?

**Comment by trel** [comment]
Everything we're using is full path - I don't think we have a relative path issue.

Can you trap the issue?  Show an example?

**Comment by alanking** [comment]
Issue #67 duplicates this issue so we will close this one and continue work there.
