### ISSUE TITLE
Possible race condition between syncing data objects and their parent collections

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_automated_ingest#71]
https://github.com/irods/irods_capability_automated_ingest/blob/1d2a2158307b2c5991d9cc14a8331272b19d4cb0/irods_capability_automated_ingest/sync_task.py#L298-L300

`sync_dir` is called asynchronously from `sync_path` to register a collection ahead of the files and/or subcollections it contains. Depending on the availability of workers and priority of the queues, it is possible for a data object to be registered before its parent collection is created via `sync_dir` because data objects will create their own parent collections as needed. Investigate making `sync_dir` part of `sync_path` by removing the `async` call.

**Comment by alanking** [comment]
Looking at this again, the priority of the queues would not affect this situation. The creation of the collection is put on the `file` queue before we even fetch the items in the directory (or bucket). The `file` queue is the same queue where data object creation tasks are placed.

According to the [Celery FAQs](https://docs.celeryq.dev/en/stable/faq.html#does-celery-support-task-priorities), you can prioritize tasks within the same queue, but the Automated Ingest framework doesn't do that. The user would have to jump through some hoops to prioritize the `sync_file` task, so I have no concerns about it *starting* before the `sync_dir` task.

This issue was raised in #175 as well, and we concluded that the situation is extremely unlikely and is handled as an exception if it occurs: https://github.com/irods/irods_capability_automated_ingest/issues/175#issuecomment-1192613146 Our conclusion in that issue was that the solution is reasonable.

I think we may be able to close both of these issues.

**Comment by korydraughn** [comment]
The current implementation is working.

Please proceed with closing the issues.
