### ISSUE TITLE
list subcommand should show current status

### ISSUE THREAD

**Issue by trel** [irods/irods_capability_automated_ingest#91]
it would be helpful to see total count and remaining tasks in the queue for each job name

**Comment by alanking** [comment]
Is this kind of what you had in mind?
```json
{
  "periodic": [
    {
      "job_name": "84e7678e-81d5-11ef-8579-0242ac1d0006",
      "total_tasks": 5,
      "remaining_tasks": 1,
      "failed_tasks": 0,
      "retried_tasks": 0,
      "elapsed_time": 25.148015022277832
    }
  ],
  "singlepass": [
    {
      "job_name": "8e702d86-81d5-11ef-89ba-0242ac1d0006",
      "total_tasks": 5,
      "remaining_tasks": 1,
      "failed_tasks": 0,
      "retried_tasks": 0,
      "elapsed_time": 9.176376104354858
    }
  ]
}
```

**Comment by trel** [comment]
that's lovely.   perhaps also 'start_time' if that's easily available...

**Comment by trel** [comment]
`completed_tasks`?

is there a truth that can be asserted about `completed + remaining + failed = total`?

and then `retried` is just ... bonus information...

**Comment by trel** [comment]
is failed a subset of completed?  or are they disjoint?   so completed is actually ... `successful`?

**Comment by alanking** [comment]
I think... showing the same information as is seen with the `watch` subcommand may be enough, which is what is being shown in my example output above. Can think on adding the other fields, but then wouldn't we want to see those in the `watch` output as well?

**Comment by trel** [comment]
> wouldn't we want to see those in the `watch` output as well?

yes?   i mean... if we think the output is better/good/helpful... then consistency would also be nice.

**Comment by trel** [comment]
also, that is a VERY precise amount of elapsed time.

**Comment by alanking** [comment]
> also, that is a VERY precise amount of elapsed time.

Right, just reporting what `time.time()` returns. We can format this, of course.

> yes? i mean... if we think the output is better/good/helpful... then consistency would also be nice.

We should discuss what exactly we want to show both in `list` and `watch`.

**Comment by trel** [comment]
discuss - agreed.

**Comment by alanking** [comment]
After discussion, we have decided that we should show start time in addition to elapsed time, and the strings shown in the `watch` subcommand output should align more closely with what is shown here.

**Comment by alanking** [comment]
I think this is done now. We can open issues with specific improvements as desired.
